workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

test:
  image: python:3.14-slim

  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip

  before_script:
    - python --version ; pip --version
    - pip install -i https://pypi.devneeds.ir/simple virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -i https://pypi.devneeds.ir/simple pytest

  script:
    - pip install -i https://pypi.devneeds.ir/simple -e .
    - pytest


darkube_build:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
    - main
  script:
  - IMAGE_ADDRESS="registry.hamdocker.ir/my-personal-org/expenses-manager"
  - 'darkube build --push -t $IMAGE_ADDRESS:$CI_COMMIT_SHORT_SHA -t $IMAGE_ADDRESS:$CI_COMMIT_REF_SLUG
    --workdir . --file ./dockerfiles/Dockerfile --build-context . '
  stage: build
darkube_deploy:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
    - main
  script:
  - darkube deploy --token ${DEPLOY_TOKEN_EXPENSES_MANAGER_MY_PERSONAL_ORG_EXPENSES_MANAGER_MAK_HAMRAVESH_C13}
    --app-id ${APP_ID_EXPENSES_MANAGER_MY_PERSONAL_ORG_EXPENSES_MANAGER_MAK_HAMRAVESH_C13}
    --image-tag ${CI_COMMIT_SHORT_SHA} --job-id ${CI_JOB_ID}
  stage: deploy
